#
# Copyright (c) 2019 Stackinsights to present
# All rights reserved
#

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Name }}-elasticsearch
  namespace: {{ .Namespace }}
  labels:
    operator.stackinsights.apache.org/es-name: {{ .Name }}
    operator.stackinsights.apache.org/application: elasticsearch
    operator.stackinsights.apache.org/component: rbac
