#
# Copyright (c) 2019 Stackinsights to present
# All rights reserved
#
resources:
- manifests.yaml
- service.yaml

configurations:
- kustomizeconfig.yaml

patchesStrategicMerge:
  - ns_selector_patch.yaml
