#
# Copyright (c) 2019 Stackinsights to present
# All rights reserved
#

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-operator-stackinsights-apache-org-v1alpha1-banyandb
  failurePolicy: Fail
  name: mbanyandb.kb.io
  rules:
  - apiGroups:
    - operator.stackinsights.apache.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - banyandbs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-operator-stackinsights-apache-org-v1alpha1-fetcher
  failurePolicy: Fail
  name: mfetcher.kb.io
  rules:
  - apiGroups:
    - operator.stackinsights.apache.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - fetchers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-operator-stackinsights-apache-org-v1alpha1-javaagent
  failurePolicy: Fail
  name: mjavaagent.kb.io
  rules:
  - apiGroups:
    - operator.stackinsights.apache.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - javaagents
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-operator-stackinsights-apache-org-v1alpha1-oapserver
  failurePolicy: Fail
  name: moapserver.kb.io
  rules:
  - apiGroups:
    - operator.stackinsights.apache.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - oapservers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-operator-stackinsights-apache-org-v1alpha1-oapserverconfig
  failurePolicy: Fail
  name: moapserverconfig.kb.io
  rules:
  - apiGroups:
    - operator.stackinsights.apache.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - oapserverconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-operator-stackinsights-apache-org-v1alpha1-oapserverdynamicconfig
  failurePolicy: Fail
  name: moapserverdynamicconfig.kb.io
  rules:
  - apiGroups:
    - operator.stackinsights.apache.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - oapserverdynamicconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-operator-stackinsights-apache-org-v1alpha1-satellite
  failurePolicy: Fail
  name: msatellite.kb.io
  rules:
  - apiGroups:
    - operator.stackinsights.apache.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - satellites
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-operator-stackinsights-apache-org-v1alpha1-storage
  failurePolicy: Fail
  name: mstorage.kb.io
  rules:
  - apiGroups:
    - operator.stackinsights.apache.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - storages
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-operator-stackinsights-apache-org-v1alpha1-swagent
  failurePolicy: Fail
  name: mswagent.kb.io
  rules:
  - apiGroups:
    - operator.stackinsights.apache.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - swagents
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-operator-stackinsights-apache-org-v1alpha1-ui
  failurePolicy: Fail
  name: mui.kb.io
  rules:
  - apiGroups:
    - operator.stackinsights.apache.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - uis
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v1-pod
  failurePolicy: Fail
  name: mpod.kb.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-operator-stackinsights-apache-org-v1alpha1-banyandb
  failurePolicy: Fail
  name: vbanyandb.kb.io
  rules:
  - apiGroups:
    - operator.stackinsights.apache.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - banyandbs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-operator-stackinsights-apache-org-v1alpha1-fetcher
  failurePolicy: Fail
  name: vfetcher.kb.io
  rules:
  - apiGroups:
    - operator.stackinsights.apache.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - fetchers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-operator-stackinsights-apache-org-v1alpha1-javaagent
  failurePolicy: Fail
  name: vjavaagent.kb.io
  rules:
  - apiGroups:
    - operator.stackinsights.apache.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - javaagents
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-operator-stackinsights-apache-org-v1alpha1-oapserver
  failurePolicy: Fail
  name: voapserver.kb.io
  rules:
  - apiGroups:
    - operator.stackinsights.apache.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - oapservers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-operator-stackinsights-apache-org-v1alpha1-oapserverconfig
  failurePolicy: Fail
  name: voapserverconfig.kb.io
  rules:
  - apiGroups:
    - operator.stackinsights.apache.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - oapserverconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-operator-stackinsights-apache-org-v1alpha1-oapserverdynamicconfig
  failurePolicy: Fail
  name: voapserverdynamicconfig.kb.io
  rules:
  - apiGroups:
    - operator.stackinsights.apache.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - oapserverdynamicconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-operator-stackinsights-apache-org-v1alpha1-satellite
  failurePolicy: Fail
  name: vsatellite.kb.io
  rules:
  - apiGroups:
    - operator.stackinsights.apache.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - satellites
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-operator-stackinsights-apache-org-v1alpha1-storage
  failurePolicy: Fail
  name: vstorage.kb.io
  rules:
  - apiGroups:
    - operator.stackinsights.apache.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - storages
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-operator-stackinsights-apache-org-v1alpha1-swagent
  failurePolicy: Fail
  name: vswagent.kb.io
  rules:
  - apiGroups:
    - operator.stackinsights.apache.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - swagents
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-operator-stackinsights-apache-org-v1alpha1-ui
  failurePolicy: Fail
  name: vui.kb.io
  rules:
  - apiGroups:
    - operator.stackinsights.apache.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - uis
  sideEffects: None
