#
# Copyright (c) 2019 Stackinsights to present
# All rights reserved
#

apiVersion: v1
kind: Namespace
metadata:
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: custom-metrics-apiserver
  name: apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-metrics-apiserver
  template:
    metadata:
      labels:
        app: custom-metrics-apiserver
      name: custom-metrics-apiserver
    spec:
      serviceAccountName: apiserver
      containers:
        - name: adapter
          image: metrics-adapter:latest
          imagePullPolicy: IfNotPresent
          command: ["/adapter"]
          args:
            - --secure-port=6443
            - --logtostderr=true
            - --v=10
            - --oap-addr=http://stackinsights-system-oap.stackinsights-system:12800/graphql  #the address is used for testing, please use your oap address
            - --cert-dir=/tmp
          ports:
            - containerPort: 6443
              name: https
          volumeMounts:
            - mountPath: /tmp
              name: temp-vol
      volumes:
        - name: temp-vol
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: apiserver
spec:
  ports:
    - name: https
      port: 443
      targetPort: 6443
  selector:
    app: custom-metrics-apiserver
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: apiserver
---
