#
#
# Copyright (c) 2019 Stackinsights to present
# All rights reserved
#
#

github:
  description: Apache StackInsights Cloud on Kubernetes
  homepage: https://stackinsights.apache.org/
  labels:
    - stackinsights
    - observability
    - apm
    - distributed-tracing
    - kubernetes
    - operator
  enabled_merge_buttons:
    squash:  true
    merge:   false
    rebase:  false
  protected_branches:
    master:
      required_status_checks:
        strict: true
        contexts:
          - build 
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        required_approving_review_count: 1

