#
# Copyright (c) 2019 Stackinsights to present
# All rights reserved
#

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Name }}-satellite
  namespace: {{ .Namespace }}
  labels:
    operator.stackinsights.apache.org/satellite-server-name: {{ .Name }}
    operator.stackinsights.apache.org/application: satellite
    operator.stackinsights.apache.org/component: rbac
