#
# Copyright (c) 2019 Stackinsights to present
# All rights reserved
#
# permissions for end users to view javaagents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: javaagent-viewer-role
rules:
- apiGroups:
  - operator.stackinsights.apache.org
  resources:
  - javaagents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.stackinsights.apache.org
  resources:
  - javaagents/status
  verbs:
  - get
