#
# Copyright (c) 2019 Stackinsights to present
# All rights reserved
#
# permissions for end users to view oapserverconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oapserverconfig-viewer-role
rules:
- apiGroups:
  - operator.stackinsights.apache.org
  resources:
  - oapserverconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.stackinsights.apache.org
  resources:
  - oapserverconfigs/status
  verbs:
  - get
