#
# Copyright (c) 2019 Stackinsights to present
# All rights reserved
#
# permissions for end users to edit storages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storage-editor-role
rules:
- apiGroups:
  - operator.stackinsights.apache.org
  resources:
  - storages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.stackinsights.apache.org
  resources:
  - storages/status
  verbs:
  - get
