#
# Copyright (c) 2019 Stackinsights to present
# All rights reserved
#

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - kind: ServiceAccount
    name: stackinsights-custom-metrics-apiserver
    namespace: stackinsights-custom-metrics-system

