#
# Copyright (c) 2019 Stackinsights to present
# All rights reserved
#

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: satellite-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stackinsights-system-satellite
  # Satellite count range limit
  minReplicas: 1
  maxReplicas: 3
  # Limit continuous scaling up
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      selectPolicy: Min
  metrics:
    # Average number of connections threshold
    - type: External
      external:
        metric:
          name: stackinsights.apache.org|satellite_service_grpc_connect_count
          selector:
            matchLabels:
              "service.str.0": "satellite"
              "service.byte.1": "3a"
              "service.byte.2": "3a"
              "service.str.3": "satellite"
              "service.byte.4": "2d"
              "service.str.5": "service"
        target:
          type: Value
          value: 1900
    # Average CPU usage threshold
    - type: External
      external:
        metric:
          name: stackinsights.apache.org|satellite_service_server_cpu_utilization
          selector:
            matchLabels:
              "service.str.0": "satellite"
              "service.byte.1": "3a"
              "service.byte.2": "3a"
              "service.str.3": "satellite"
              "service.byte.4": "2d"
              "service.str.5": "service"
        target:
          type: Value
          value: 75
