#
# Copyright (c) 2019 Stackinsights to present
# All rights reserved
#

{{- if .Spec.GRPCSvc }}

{{- $svc := .Spec.GRPCSvc.Template }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Name }}-banyandb-grpc
  namespace: {{ .Namespace }}
  labels:
    app: banyandb
    operator.stackinsights.apache.org/banyandb-name: {{ .Name }}
    operator.stackinsights.apache.org/application: banyandb
    operator.stackinsights.apache.org/component: service
spec:
  type: {{ $svc.Type }}
  selector:
    app: banyandb
    operator.stackinsights.apache.org/banyandb-name: {{ .Name }}
  ports:
    - port: 17912
      name: grpc

  {{- if $svc.ExternalIPs }}
  externalIPs:
    {{- range $value := $svc.ExternalIPs }}
    - {{ $value | quote }}
    {{- end }}
  {{- end }}

  {{- if $svc.LoadBalancerIP }}
  loadBalancerIP: {{ $svc.LoadBalancerIP }}
  {{- end }}

  {{- if $svc.LoadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- range $value := $svc.LoadBalancerSourceRanges }}
    - {{ $value | quote }}
    {{- end }}
  {{- end }}

{{- end }}
