#
# Copyright (c) 2019 Stackinsights to present
# All rights reserved
#

{{- $ingress := .Spec.HTTPSvc.Ingress }}
{{ if $ingress.Host }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Name }}-banyandb
  namespace: {{ .Namespace }}
  labels:
    app: ui
    operator.stackinsights.apache.org/ui-name: {{ .Name }}
    operator.stackinsights.apache.org/application: ui
    operator.stackinsights.apache.org/component: deployment
  annotations:
    {{- range $key, $value := $ingress.Annotations }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
spec:
  rules:
    - host: {{ $ingress.Host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Name }}-banyandb-http
                port:
                  number: 17913
            path: /
            pathType: Prefix
  {{- if $ingress.IngressClassName }}
  ingressClassName: {{ $ingress.IngressClassName }}
  {{end}}
  {{- if $ingress.TLS }}
  tls:
  {{ toYAML $ingress.TLS | indent 4 }}
  {{end}}
  {{end}}
