#
# Copyright (c) 2019 Stackinsights to present
# All rights reserved
#

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Name }}-banyandb
  namespace: {{ .Namespace }}
  labels:
    operator.stackinsights.apache.org/oap-server-name: {{ .Name }}
    operator.stackinsights.apache.org/application: banyandb
    operator.stackinsights.apache.org/component: rbac

