#
# Copyright (c) 2019 Stackinsights to present
# All rights reserved
#

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Name }}-fetcher
  namespace: {{ .Namespace }}
  labels:
    operator.stackinsights.apache.org/fetcher-name: {{ .Name }}
    operator.stackinsights.apache.org/application: fetcher
    operator.stackinsights.apache.org/component: rbac
