#
# Copyright (c) 2019 Stackinsights to present
# All rights reserved
#

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resource-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: resource-reader
subjects:
  - kind: ServiceAccount
    name: apiserver
    
