#
# Copyright (c) 2019 Stackinsights to present
# All rights reserved
#

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: server-resources
rules:
  - apiGroups:
      - custom.metrics.k8s.io
      - external.metrics.k8s.io
    resources: ["*"]
    verbs: ["*"]
